name: Set up Percona Toolkit
author: Roberto Graham
description: Sets up Percona Toolkit in your GitHub Actions workflow.
inputs:
  product-version:
    description: Product Version of Percona Toolkit to set up.
    required: false
    default: '3.7.0'
runs:
  using: composite
  steps:
    - name: Add Action directory to PATH
      shell: bash
      run: echo "${{ github.action_path }}" >> "$GITHUB_PATH"

    - name: Run setup-percona-toolkit.sh
      shell: bash
      run: setup-percona-toolkit.sh
      env:
        PRODUCT_VERSION: ${{ inputs.product-version }} # TODO: Validate.
